#!/usr/bin/env python3
"""
gen_sky_badge_db.py — 从 Star Android 项目两份原始数据,重新生成
fw/application/src/app/chameleon/port/sky_badge_db.c.

用法:
    python3 scripts/gen_sky_badge_db.py \
        /path/to/Star/app/src/main/java/brr/star/sky/app/tool/BadgeRegistry.java \
        /path/to/Star/app/src/main/res/values-zh/strings.xml \
        fw/application/src/app/chameleon/port/sky_badge_db.c

为什么不直接手改 .c?  徽章数量会随版本更新; 每次都从 Star 同步比手维护更安全.
"""

from __future__ import annotations
import re
import sys
from pathlib import Path


SK_PATTERN = re.compile(
    r'm\.put\(\s*"([^"]+)"\s*,\s*new\s+BadgeEntry\(\s*(\d+)\s*,'
)
STR_PATTERN = re.compile(
    r'<string\s+name="([^"]+)"[^>]*>(.*?)</string>', re.DOTALL
)


def parse_java(java_text: str) -> list[tuple[str, int]]:
    return [(m.group(1), int(m.group(2))) for m in SK_PATTERN.finditer(java_text)]


def parse_strings(xml_text: str) -> dict[str, str]:
    return {m.group(1): m.group(2) for m in STR_PATTERN.finditer(xml_text)}


def c_escape(s: str) -> str:
    """对要嵌入 C 字符串字面量的 UTF-8 文本做最小转义.
    主要处理 " 和 \\, 其余 UTF-8 字节保持原样 (.c 文件保存为 UTF-8 即可)."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def render(table: list[tuple[str, int, str, str]]) -> str:
    lines = [
        "// AUTO-GENERATED by scripts/gen_sky_badge_db.py — DO NOT EDIT BY HAND.",
        "// 数据来源: Star Android 项目 BadgeRegistry.java + values-zh/strings.xml",
        f"// 共 {len(table)} 枚徽章 (SK -> 中文名/备注)",
        "",
        '#include "sky_badge_db.h"',
        "#include <string.h>",
        "",
        "const sky_badge_entry_t sky_badge_db[] = {",
    ]
    for sk, idx, name, note in table:
        lines.append(
            f'    {{ "{c_escape(sk)}", {idx}, "{c_escape(name)}", "{c_escape(note)}" }},'
        )
    lines += [
        "};",
        "",
        "const size_t sky_badge_db_count = sizeof(sky_badge_db)/sizeof(sky_badge_db[0]);",
        "",
        "const sky_badge_entry_t *sky_badge_db_find(const char *sk) {",
        "    if (sk == NULL || sk[0] == '\\0') {",
        "        return NULL;",
        "    }",
        "    for (size_t i = 0; i < sky_badge_db_count; i++) {",
        "        if (strcmp(sky_badge_db[i].sk, sk) == 0) {",
        "            return &sky_badge_db[i];",
        "        }",
        "    }",
        "    return NULL;",
        "}",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    if len(argv) != 4:
        print(__doc__, file=sys.stderr)
        return 2
    java_path = Path(argv[1])
    xml_path = Path(argv[2])
    out_path = Path(argv[3])

    sk_list = parse_java(java_path.read_text(encoding="utf-8"))
    strings = parse_strings(xml_path.read_text(encoding="utf-8"))

    table: list[tuple[str, int, str, str]] = []
    missing: list[str] = []
    for sk, idx in sk_list:
        name = strings.get(f"star_key{idx}name", "").strip()
        note = strings.get(f"star_key{idx}description", "").strip()
        if not name:
            missing.append(f"star_key{idx}name (sk={sk})")
        table.append((sk, idx, name, note))

    if missing:
        print("warning: missing names in strings.xml:", file=sys.stderr)
        for m in missing:
            print("  -", m, file=sys.stderr)

    out_path.write_text(render(table), encoding="utf-8")
    print(f"wrote {out_path} ({len(table)} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
